name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always

jobs:
  targets:
    name: ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          - target: x86_64-pc-windows-msvc
            runs-on: windows-latest
          - target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Publish artifacts and release
        uses: yksen/actions-rust-release@v0
        with:
          archive-name: harmony-${{ matrix.platform.target }}
          changes-file: ""
          executable-name: harmony
          target: ${{ matrix.platform.target }}